error if we cannot get the virtualenv
Change-Id: Ie06513a0227da75ea870d7010571f60568774519
Signed-off-by: Doug Hellmann <doug@doughellmann.com>

diff --git a/tools/python3-first/functions b/tools/python3-first/functions
--- a/tools/python3-first/functions
+++ b/tools/python3-first/functions
@@ -5,6 +5,11 @@ function enable_tox {
         tox -e venv --notest
     fi
     source .tox/venv/bin/activate
+    if [ -z "$VIRTUAL_ENV" ]; then
+        echo "ERROR: The virtual environment was not activated."
+        echo "Check .tox/venv/bin/activate"
+        exit 1
+    fi
 }
 
 function normalize_team {
