error out if we cannot create the tox env
Change-Id: I549e640ef665861d4454f8a3d618af8498120d38
Signed-off-by: Doug Hellmann <doug@doughellmann.com>

diff --git a/tools/python3-first/functions b/tools/python3-first/functions
--- a/tools/python3-first/functions
+++ b/tools/python3-first/functions
@@ -2,7 +2,10 @@
 
 function enable_tox {
     if [ ! -d .tox/venv ]; then
-        tox -e venv --notest
+        if ! tox -e venv --notest; then
+            echo "ERROR: Failed to create tox environment 'venv'"
+            exit 1
+        fi
     fi
     source .tox/venv/bin/activate
     if [ -z "$VIRTUAL_ENV" ]; then
